recipe: default.v1

assistant_id: placeholder_default

language: vi  # Chỉnh lại thành tiếng Việt

pipeline:
  - name: "HFTransformersNLP"
    model_name: "vinai/phobert-base"
    model_weights: "vinai/phobert-base"
    tokenizer: "vinai/phobert-base"
  - name: "LanguageModelFeaturizer"
    pooling_strategy: "mean"
    model_name: "vinai/phobert-base"
    model_weights: "vinai/phobert-base"
  - name: "DIETClassifier"
    epochs: 50
    constrain_similarities: true
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 50
  - name: "FallbackClassifier"
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: "MemoizationPolicy"
  - name: "RulePolicy"
  - name: "TEDPolicy"
    max_history: 5
    epochs: 100
